# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use a Python image with uv pre-installed
FROM ghcr.io/astral-sh/uv:python3.13-bookworm-slim AS uv

# Set working directory
WORKDIR /app

# Enable bytecode compilation
ENV UV_COMPILE_BYTECODE=1

# Copy pyproject.toml and lock file for dependencies
COPY pyproject.toml uv.lock ./
COPY README.md ./

# Install the project's dependencies
RUN --mount=type=cache,target=/root/.cache/uv \
uv sync --frozen --no-install-project --no-dev --no-editable

# Add the rest of the project source code and install it
ADD src /app/src

# Sync and install the project
RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --frozen --no-dev --no-editable

FROM python:3.13-slim-bookworm

WORKDIR /app

# Copy requirements and install them
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the code
COPY pyproject.toml uv.lock README.md ./
ADD src /app/src
COPY data-platform-* ./

# Set PYTHONPATH so the src modules are importable
ENV PYTHONPATH="/app/src"

ENTRYPOINT ["python", "-m", "mcp_server_bigquery"]

# Example command
# CMD ["--project", "your-gcp-project-id", "--location", "your-gcp-location"]
